### ISSUE TITLE
Docs are unclear about just what this does

### ISSUE THREAD

**Issue by pmocek** [nvdaes/get-repository-id#7]
The README for this repository states both that "This action gets the ID of the specified GitHub repository" and that "the ID provided by this action won't be the same as $GITHUB_REPOSITORY_ID."

It is not clear what $GITHUB_REPOSITORY_ID means, or why one would need a custom action in order to find and use the ID of the relevant repository.

GitHub actions makes the relevant repository ID available as a [default environment variable](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) named `GITHUB_REPOSITORY_ID`, but that, not `$GITHUB_REPOSITORY_ID` is the name of the variable, and `vars.GITHUB_REPOSITORY_ID` is how one would reference it in a GHA workflow, not `$GITHUB_REPOSITORY_ID`.

**Comment by nvdaes** [comment]
Hello, thanks for your comments.
I think that $GITHUB_REPOSITORY_ID.can be used in GHA without vars. I use it in cy.yml for testing.
I'll add a link to the following document in the readme:

https://docs.github.com/en/graphql/guides/using-global-node-ids

The id provided by this action is named node_id in rest.
This may be useful, for example, to be used with the [Create discussion action](https://github.com/marketplace/actions/create-github-discussion).
I don'twant to provide this as an example since seems that the action is not maintained, and for this reason I created another action to create GitHub discussions:
